# Generated by Django 4.2.15 on 2024-08-18 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_alter_fixture_id_alter_stadium_id_alter_team_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='favoriteteam',
            name='user',
        ),
        migrations.AddField(
            model_name='favoriteteam',
            name='team_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='favoriteteam',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favoriteteam',
            name='team_name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Fixture',
        ),
        migrations.DeleteModel(
            name='Stadium',
        ),
        migrations.AddField(
            model_name='userfavoriteteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.favoriteteam'),
        ),
        migrations.AddField(
            model_name='userfavoriteteam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userfavoriteteam',
            unique_together={('user', 'team')},
        ),
    ]
