# Generated by Django 4.2.15 on 2024-08-18 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userfavoriteteam_userreview_remove_favoriteteam_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavoriteteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.team'),
        ),
    ]
