# Generated by Django 4.2.15 on 2024-08-18 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_alter_userfavoriteteam_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavoriteteam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
