# Generated by Django 4.2.15 on 2024-08-31 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_alter_userfavoriteteam_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StadiumReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('image', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FavoriteTeam',
        ),
        migrations.DeleteModel(
            name='UserReview',
        ),
        migrations.AddField(
            model_name='stadiumreview',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.venue'),
        ),
    ]
